# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

template: /home/irvin/Documents/Universidad/VIISemester/IngSoftI/Proyecto/Inge1/templates