# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

template: C:\Users\Ricardo\Desktop\IngeI\Inge1\src\main\assets\templates