# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

template: /home/irvin/Documents/Universidad/VII Semester/Ing. Soft. I/Proyecto/Inge1/src/main/resources/assets/templates