<!DOCTYPE html>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<html>
<head>
    <link href="assets/bootstrap-3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="assets/font-awesome-4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="assets/css/searchBase.css">
    <title>MorphoSpace</title>
    <meta name = "viewport" content = "width = device-width, initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no">
</head>
<body>

<div class="row" id="searchControlArea">
    <div class="col-md-12 searchControls">
        <div class="row">
            <div class="col-md-offset-2 col-md-2">
                <div class="row">
                    <div class="searchImage">
                    <img src="https://nusavifauna.files.wordpress.com/2012/08/bird_anatomy_1.jpeg?w=1400">
                    </div>
                </div>
                
            </div>
            <div class="col-md-4">
                <div class="row">
                    Author
                </div>
                
            </div>
        </div>
        
    </div>
</div>

<div class="row" id="searchResults">
    <div class="col-md-12 resultsPage">
        <div class="row">
            <div class="col-md-12">
                <div class="resultsCard">
                    <div class="resultsCardTop">
                        <div class="resultsCardImage">
                            <img src="http://data.whicdn.com/images/34473435/original.jpg">
                        </div>
                    </div>
                    <div class="resultsCardInfo">
                        Similarity: 1000%
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>

</body>

<script src="https://apis.google.com/js/platform.js" async defer></script>
<script src="assets/jquery/jquery-3.2.1.js"></script>
<script src="assets/bootstrap-3.3.7/js/bootstrap.js"></script>
<script src="assets/js/js.cookie.js" ></script>
<script src="assets/js/searchBase.js"></script>

</html>