      <div class="row" id="searchControlArea">
          <div class="col-md-12 searchControls">
              <div class="row">
                  <div class="col-md-2">

                      <div title="Go back to making the composition" id="goBack" onclick="changeContainers()" >
                          <i class="fa fa-chevron-circle-left fa-2x" aria-hidden="true"></i>
                      </div>

                  </div>
                  <div class="col-md-2">
                      <div class="row">
                          <div class="searchImage">
                          <img src="https://nusavifauna.files.wordpress.com/2012/08/bird_anatomy_1.jpeg?w=1400">
                          </div>
                      </div>
                      
                  </div>
                  <div class="col-md-2 currentCompositionInfo hideInfo">
                      <label for="currentAuthorField">Author of current composition: </label>
                      <span id="currentAuthorField">Irvin</span>     
                  </div>
                  <div class="col-md-offset-1 col-md-3">
                      <span id="resultInformationBlock" class="hideInfo">
                          <h3> Result information </h3>
                          <div class="row" id="compositionResultInfomration">
                              <div class="col-md-12">
                                  <label for="authorField">Author: </label>
                                  <span id="authorField">Irvin</span>     
                              </div>
                              <div class="col-md-12">
                                  <label for="scieNameField">Scientific Name: </label>
                                  <span id="sciNameField">Pikachu</span>  
                              </div>
                              <div class="col-md-12">
                                  <label for="similarityScoreField">Similarity Score: </label>
                                  <span id="similarityScorField">100%</span>  
                              </div>


                          </div>
                      </span>
                  </div>
              </div>
              
          </div>
      </div>

      <div class="row" id="searchResults">
          <div class="col-md-offset-1 col-md-10 resultsBlock">
                  <div class="row resultsBlockRow">
                      <div class="col-md-3 resultsCardSpace resultsCardSpaceTemplate hideInfo">
                          <div class="resultsCard">
                              <div class="resultsCardTop">
                                  <div class="resultsCardImage">
                                      <img src="http://data.whicdn.com/images/34473435/original.jpg">
                                  </div>
                              </div>
                              <div class="resultsCardInfo">
                                  <div class="hideInfo">
                                      <label for="authorFieldCard">Author: </label>
                                      <span class="authorFieldCard">Ricardo</span>     
                                  </div>
                                  <div class="hideInfo" >
                                      <label for="scieNameFieldCard">Scientific Name: </label>
                                      <span class="sciNameFieldCard">Pichoto</span>  
                                  </div>
                                  <div>
                                      <label for="similarityScoreFieldCard">Similarity Score: </label>
                                      <span class="similarityScorFieldCard">33%</span>  
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
          </div>
      </div>