      <div class="row" id="searchControlArea">
          <div class="col-md-12 searchControls">
              <div class="row">
                  <div class="col-md-1">

                      <div title="Go back to making the composition" id="goBack" onclick="changeContainers()" >
                          <i class="fa fa-chevron-circle-left fa-2x" aria-hidden="true"></i>
                      </div>

                  </div>
                  <div class="col-md-2">
                      <div class="row">
                          <div class="searchImage">
                          <img src="https://nusavifauna.files.wordpress.com/2012/08/bird_anatomy_1.jpeg?w=1400">
                          </div>
                      </div>
                      
                  </div>
                  <div class="col-md-8">
                  	<div class="row" id="resultInformationBlock">
                      <div class="col-md-4 ">
                          <h4> Result information </h4>
                          <div class="row" id="compositionResultInfomration">
                              <div class="col-md-12">
                                  <label for="authorField">Author: </label>
                                  <span id="authorField">Irvin</span>     
                              </div>
                              <div class="col-md-12">
                                  <label for="scieNameField">Scientific Name: </label>
                                  <span id="sciNameField">Pikachu</span>  
                              </div>
                              <div class="col-md-12">
                                  <label for="similarityScoreField">Similarity Score: </label>
                                  <span id="similarityScorField">100%</span>  
                              </div>
                          </div>
                      </div>
		              <div class="col-md-8">
		              		<h4> Related Images </h4>
		              		<div id="relatedImages">
		              			
		              		</div>
		              </div>                		
                  	</div>

                  </div>
              </div>
              
          </div>
      </div>

      <div class="row" id="searchResults">
          <div class="col-md-offset-1 col-md-10 resultsBlock">
                  <div class="row resultsBlockRow">
                      <div class="col-md-3 resultsCardSpace resultsCardSpaceTemplate hideInfo">
                          <div class="resultsCard">
                              <div class="resultsCardTop">
                                  <div class="resultsCardImage">
                                      <img src="http://data.whicdn.com/images/34473435/original.jpg">
                                  </div>
                              </div>
                              <div class="resultsCardInfo">
                              		<div class="hideInfo">
                              			<div class="compositionId"></div>
                              		</div>
                                  <div class="hideInfo">
                                      <label for="authorFieldCard">Author: </label>
                                      <span class="authorFieldCard">Ricardo</span>     
                                  </div>
                                  <div class="" >
                                      <label for="scieNameFieldCard">Scientific Name: </label>
                                      <span class="sciNameFieldCard">Pichoto</span>  
                                  </div>
                                  <div>
                                      <label for="similarityScoreFieldCard">Similarity Score: </label>
                                      <span class="similarityScorFieldCard">33%</span>  
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
          </div>
      </div>

      <div id="hiddenImages" class="hideInfo">
      	
      	<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
		              			<img class="resultsRelatedImages" src="http://webneel.com/daily/sites/default/files/images/daily/04-2014/1-bird-drawing.jpg">
      </div>